{{- if not .Values.kafka.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-loader.kafkaSecretName" . }}
  labels:
    {{- include "dfe-loader.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.kafka.secretKeys.username }}: {{ .Values.kafka.username | b64enc | quote }}
  {{ .Values.kafka.secretKeys.password }}: {{ .Values.kafka.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.clickhouse.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-loader.clickhouseSecretName" . }}
  labels:
    {{- include "dfe-loader.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.clickhouse.secretKeys.password }}: {{ .Values.clickhouse.password | b64enc | quote }}
{{- end }}
