apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfe-loader.fullname" . }}
  labels:
    {{- include "dfe-loader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if eq (toString (.Values.config).transport) "grpc" }}
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: push
    {{- end }}
  selector:
    {{- include "dfe-loader.selectorLabels" . | nindent 4 }}
