-- Common Header Schema v2 - Reference DDL
--
-- This is the minimal required schema for DFE v2 tables.
-- Additional dynamic fields will be added via ALTER TABLE as needed.
--
-- Usage:
--   Replace {db} and {table} with actual database and table names.
--   Example: CREATE TABLE acme.events_auth ...
--
-- Requirements:
--   - ClickHouse 24.8+ for generateUUIDv7()
--   - JSON type support (experimental in 24.x, stable in 25.x)

CREATE TABLE IF NOT EXISTS {db}.{table}
(
    -- Event timestamp (millisecond precision)
    -- Source: extracted from event data, fallback to now64(3)
    `timestamp` DateTime64(3) CODEC(Delta, ZSTD(1)),

    -- Load timestamp (when event was inserted)
    -- Generated by ClickHouse DEFAULT - all rows in batch get same value
    `timestamp_load` DateTime64(3) DEFAULT now64(3) CODEC(Delta, ZSTD(1)),

    -- Unique event ID (UUIDv7 - time-ordered, sortable)
    -- Generated by ClickHouse DEFAULT - no client generation needed
    `_uuid` UUID DEFAULT generateUUIDv7(),

    -- Organisation ID (for multi-tenancy and row-level security)
    -- Extracted from org_id field in source data
    -- Used by ClickHouse row policies for data isolation
    -- REQUIRED for shared schema deployments (common database)
    `_org_id` String CODEC(ZSTD(1)),

    -- Original unparsed log line (if available)
    `logoriginal` Nullable(String) CODEC(ZSTD(3)),

    -- Complete original Kafka message as JSON
    -- Captured before any transformation
    `logjson` Nullable(JSON) CODEC(ZSTD(3)),

    -- Message metadata and collector/agent information
    -- Extracted from tags/meta fields before flattening
    `_tags` Nullable(JSON) CODEC(ZSTD(3))

    -- Dynamic fields added here via ALTER TABLE ADD COLUMN
)
ENGINE = MergeTree()
ORDER BY (timestamp, _org_id, _uuid)  -- Include _org_id for RLS performance
PARTITION BY (toYYYYMM(timestamp), _org_id)  -- Partition by month + org for pruning
SETTINGS index_granularity = 8192;

-- Notes:
--
-- 1. _org_id is REQUIRED for shared schema deployments (common database).
--    - Extracted from org_id field in source data (configurable)
--    - Used by ClickHouse row policies for data isolation (RLS)
--    - See reference/clickhouse_rls.md for row policy setup
--
-- 2. Routing fields (event_category) determine the table name.
--    - org_id determines database ONLY if in routed_orgs list
--    - Default: all data goes to common.{table}
--    - See CLAUDE.md section "Dynamic db.table Routing" for details
--
-- 3. timestamp_load uses ClickHouse DEFAULT now64(3).
--    All rows in an INSERT batch get the same timestamp (per-batch, not per-row).
--    This is acceptable for windowing queries.
--
-- 4. _uuid uses generateUUIDv7() which is thread-monotonic in ClickHouse 24.8+.
--    Time-ordered UUIDs are ideal for event IDs (sortable, unique).
--
-- 5. JSON columns (logjson, _tags) require ClickHouse JSON type support.
--    Use ZSTD(3) compression for good ratio on JSON data.
--
-- 6. Underscore-prefixed fields (_uuid, _org_id, _tags) avoid collision with source data.
--    The loader preserves these during field sanitization.
--
-- 7. ORDER BY includes _org_id for efficient row policy filtering.
--    PARTITION BY includes _org_id for partition pruning (queries only read relevant org).
--    See reference/clickhouse_rls.md for performance details.
