-- Common Header Schema v2 - Reference DDL
--
-- This is the minimal required schema for DFE v2 tables.
-- Additional dynamic fields will be added via ALTER TABLE as needed.
--
-- Usage:
--   Replace {db} and {table} with actual database and table names.
--   Example: CREATE TABLE acme.events_auth ...
--
-- Requirements:
--   - ClickHouse 24.8+ for generateUUIDv7()
--   - JSON type support (experimental in 24.x, stable in 25.x)

CREATE TABLE IF NOT EXISTS {db}.{table}
(
    -- Event timestamp (millisecond precision)
    -- Source: extracted from event data, fallback to now64(3)
    `timestamp` DateTime64(3) CODEC(Delta, ZSTD(1)),

    -- Load timestamp (when event was inserted)
    -- Generated by ClickHouse DEFAULT - all rows in batch get same value
    `timestamp_load` DateTime64(3) DEFAULT now64(3) CODEC(Delta, ZSTD(1)),

    -- Unique event ID (UUIDv7 - time-ordered, sortable)
    -- Generated by ClickHouse DEFAULT - no client generation needed
    `_uuid` UUID DEFAULT generateUUIDv7(),

    -- Original unparsed log line (if available)
    `logoriginal` Nullable(String) CODEC(ZSTD(3)),

    -- Complete original Kafka message as JSON
    -- Captured before any transformation
    `logjson` Nullable(JSON) CODEC(ZSTD(3)),

    -- Message metadata and collector/agent information
    -- Extracted from tags/meta fields before flattening
    `_tags` Nullable(JSON) CODEC(ZSTD(3))

    -- Dynamic fields added here via ALTER TABLE ADD COLUMN
)
ENGINE = MergeTree()
ORDER BY (timestamp, _uuid)
PARTITION BY toYYYYMM(timestamp)
SETTINGS index_granularity = 8192;

-- Notes:
--
-- 1. Routing fields (org_id, event_category) are NOT stored in the table.
--    They are used only for routing to db.table, then removed.
--
-- 2. timestamp_load uses ClickHouse DEFAULT now64(3).
--    All rows in an INSERT batch get the same timestamp (per-batch, not per-row).
--    This is acceptable for windowing queries.
--
-- 3. _uuid uses generateUUIDv7() which is thread-monotonic in ClickHouse 24.8+.
--    Time-ordered UUIDs are ideal for event IDs (sortable, unique).
--
-- 4. JSON columns (logjson, _tags) require ClickHouse JSON type support.
--    Use ZSTD(3) compression for good ratio on JSON data.
--
-- 5. Underscore-prefixed fields (_uuid, _tags) avoid collision with source data.
--    The loader preserves these during field sanitization.
