-- Common Table Schema v2
--
-- Template variables: {db}, {table}, {engine}, {table_comment}
--
-- Table-level tags (stored in table COMMENT):
--   @schema_source: core     - Pre-supplied schema from dfe-loader
--   @schema_source: user     - User-created schema (or absent)
--   @schema_version: 2       - Schema version for migrations
--
-- Engine auto-detection priority:
--   1. SharedMergeTree (ClickHouse Cloud / 24.1+)
--   2. ReplicatedMergeTree (clustered with ZooKeeper/Keeper)
--   3. MergeTree (single-node fallback)
--
-- Requirements:
--   - ClickHouse 24.8+ for generateUUIDv7()
--   - ClickHouse 25.x+ for stable JSON type
--   - ClickHouse 25.1+ for full_text index (GA)
--
-- Field Mapping: See docs/DDL-EXPRESSION.md for expression language reference

CREATE TABLE IF NOT EXISTS {db}.{table}
(
    -- @generated: now64(3)
    -- Primary query timestamp (load time) - used for time window queries
    -- All user queries filter on this, so it's in ORDER BY after _org_id
    `_timestamp_load` DateTime64(3) DEFAULT now64(3) CODEC(Delta, ZSTD(1)),

    -- @source: timestamp | now()
    -- Event timestamp (when event occurred)
    -- Secondary time field, indexed with minmax for range queries
    `_timestamp` DateTime64(3) CODEC(Delta, ZSTD(1)),

    -- @source: timestamp_received
    -- Received timestamp (when the receiver/loader received the event)
    -- Nullable - only present if source includes timestamp_received
    `_timestamp_received` Nullable(DateTime64(3)) CODEC(Delta, ZSTD(1)),

    -- @generated: generateUUIDv7()
    -- Unique event ID (UUIDv7 - time-ordered, sortable)
    -- Generated by ClickHouse DEFAULT - no client generation needed
    `_uuid` UUID DEFAULT generateUUIDv7(),

    -- @source: org_id
    -- @config: routing.org_id_field (default: "org_id")
    -- Organisation ID (REQUIRED - every query uses this for RLS)
    -- First in ORDER BY for efficient multi-tenant queries
    -- LowCardinality for dictionary encoding (orgs are repeated)
    `_org_id` LowCardinality(String) CODEC(ZSTD(1)),

    -- @renamed: logoriginal
    -- @config: metadata.capture_raw (default: true), metadata.raw_source_fields
    -- Original log line (zero-copy rename from source field)
    -- Silent no-op if _raw already present in data (upstream may populate directly)
    -- Full-text searchable when enabled (see Text Search notes below)
    `_raw` Nullable(String) CODEC(ZSTD(3)),

    -- @captured: raw_payload as JSON (pre-transform)
    -- @config: metadata.capture_json (default: true)
    -- Complete Kafka message as JSON (structured queries)
    -- ClickHouse JSON type for columnar storage of dynamic fields
    `_json` Nullable(JSON) CODEC(ZSTD(3)),

    -- @source: first(tags/_tags/meta/metadata.tags)
    -- @config: metadata.tags_fields
    -- Metadata and collector/agent information
    `_tags` Nullable(JSON) CODEC(ZSTD(3)),

    -- Indexes for non-primary key columns
    INDEX idx_timestamp _timestamp TYPE minmax GRANULARITY 1
)
ENGINE = {engine}
ORDER BY (_org_id, _timestamp_load, _uuid)
PARTITION BY (toYYYYMM(_timestamp_load), _org_id)
SETTINGS index_granularity = 8192
COMMENT '{table_comment}'

-- Schema Design Notes:
--
-- ORDER BY (_org_id, _timestamp_load, _uuid):
--   - _org_id first: Every query has org_id (RLS), data grouped by org
--   - _timestamp_load second: Primary time filter within each org
--   - _uuid last: Ensures uniqueness and deterministic ordering
--
-- PARTITION BY (toYYYYMM(_timestamp_load), _org_id):
--   - Monthly partitions by load time
--   - Includes _org_id for partition pruning (<100 orgs = acceptable cardinality)
--   - Enables efficient TTL and per-org data management
--
-- LowCardinality(_org_id):
--   - Dictionary encoding for repeated org IDs
--   - Reduces storage and speeds up equality comparisons
--
-- _timestamp vs _timestamp_load:
--   - _timestamp_load: When data was loaded (query filter, ORDER BY)
--   - _timestamp: When event occurred (event time, minmax index)
--   - Most queries filter on load time for operational dashboards
--
-- Text Search (configurable, default ON):
--   - Add via ALTER TABLE when enabled:
--     ALTER TABLE {db}.{table} ADD INDEX idx_raw _raw
--       TYPE ngrambf_v1(3, 256, 2, 0) GRANULARITY 4
--   - Or when full_text is GA (25.1+):
--     ALTER TABLE {db}.{table} ADD INDEX idx_raw _raw
--       TYPE full_text(0) GRANULARITY 1
