-- Common Table Schema v2
--
-- Template variables: {db}, {table}, {engine}
--
-- Engine auto-detection priority:
--   1. SharedMergeTree (ClickHouse Cloud / 24.1+)
--   2. ReplicatedMergeTree (clustered with ZooKeeper/Keeper)
--   3. MergeTree (single-node fallback)
--
-- Requirements:
--   - ClickHouse 24.8+ for generateUUIDv7()
--   - ClickHouse 25.x+ for stable JSON type
--   - ClickHouse 25.1+ for full_text index (GA)

CREATE TABLE IF NOT EXISTS {db}.{table}
(
    -- Primary query timestamp (load time) - used for time window queries
    -- All user queries filter on this, so it's in ORDER BY after _org_id
    `timestamp_load` DateTime64(3) DEFAULT now64(3) CODEC(Delta, ZSTD(1)),

    -- Event timestamp (when event occurred)
    -- Secondary time field, indexed with minmax for range queries
    `timestamp` DateTime64(3) CODEC(Delta, ZSTD(1)),

    -- Unique event ID (UUIDv7 - time-ordered, sortable)
    -- Generated by ClickHouse DEFAULT - no client generation needed
    `_uuid` UUID DEFAULT generateUUIDv7(),

    -- Organisation ID (REQUIRED - every query uses this for RLS)
    -- First in ORDER BY for efficient multi-tenant queries
    -- LowCardinality for dictionary encoding (orgs are repeated)
    `_org_id` LowCardinality(String) CODEC(ZSTD(1)),

    -- Original log line (full-text searchable when enabled)
    `logoriginal` Nullable(String) CODEC(ZSTD(3)),

    -- Complete message as JSON (structured queries)
    -- ClickHouse JSON type for columnar storage of dynamic fields
    `logjson` Nullable(JSON) CODEC(ZSTD(3)),

    -- Metadata and collector/agent information
    `_tags` Nullable(JSON) CODEC(ZSTD(3)),

    -- Indexes for non-primary key columns
    INDEX idx_timestamp timestamp TYPE minmax GRANULARITY 1
)
ENGINE = {engine}
ORDER BY (_org_id, timestamp_load, _uuid)
PARTITION BY (toYYYYMM(timestamp_load), _org_id)
SETTINGS index_granularity = 8192

-- Schema Design Notes:
--
-- ORDER BY (_org_id, timestamp_load, _uuid):
--   - _org_id first: Every query has org_id (RLS), data grouped by org
--   - timestamp_load second: Primary time filter within each org
--   - _uuid last: Ensures uniqueness and deterministic ordering
--
-- PARTITION BY (toYYYYMM(timestamp_load), _org_id):
--   - Monthly partitions by load time
--   - Includes _org_id for partition pruning (<100 orgs = acceptable cardinality)
--   - Enables efficient TTL and per-org data management
--
-- LowCardinality(_org_id):
--   - Dictionary encoding for repeated org IDs
--   - Reduces storage and speeds up equality comparisons
--
-- timestamp vs timestamp_load:
--   - timestamp_load: When data was loaded (query filter, ORDER BY)
--   - timestamp: When event occurred (event time, minmax index)
--   - Most queries filter on load time for operational dashboards
--
-- Text Search (configurable, default ON):
--   - Add via ALTER TABLE when enabled:
--     ALTER TABLE {db}.{table} ADD INDEX idx_logoriginal logoriginal
--       TYPE ngrambf_v1(3, 256, 2, 0) GRANULARITY 4
--   - Or when full_text is GA (25.1+):
--     ALTER TABLE {db}.{table} ADD INDEX idx_logoriginal logoriginal
--       TYPE full_text(0) GRANULARITY 1
